// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnvfrklcrlwfxsktbkuv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpudmZya2xjcmx3Znhza3Ria3V2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1OTkwMTIsImV4cCI6MjA3NTE3NTAxMn0.8T2_ubURHEjHuiHxeDAJYhE43SyK9uU9jGWFB2pXiwY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});